### ISSUE TITLE
Support of relative paths for files in config file

### ISSUE THREAD

**Issue by iamsalnikov** [iamsalnikov/config-builder#1]
If we have following directory structure:

```
project/
    config_placeholders/
        user.yml
        data_sources.yml
    config_builder.yml 
```

and following config of value providers:

```yml
User:
  class: iamsalnikov\ConfigBuilder\ValueProviders\Yaml
  arguments:
    - config_placeholders/user.yml

DataSources:
  class: iamsalnikov\ConfigBuilder\ValueProviders\Yaml
  arguments:
    - config_placeholders/data_sources.yml
```

Then we will need to find files `config_placeholders/user.yml`, `config_placeholders/user.yml` in path `project`.
